/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 09 05:11:58 GMT 2021
 */

package org.apache.commons.lang3.concurrent;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.concurrent.ConcurrentRuntimeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConcurrentRuntimeException_ESTest extends ConcurrentRuntimeException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConcurrentRuntimeException concurrentRuntimeException0 = new ConcurrentRuntimeException();
      ConcurrentRuntimeException concurrentRuntimeException1 = null;
      try {
        concurrentRuntimeException1 = new ConcurrentRuntimeException(concurrentRuntimeException0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Not a checked exception: org.evosuite.runtime.mock.java.lang.MockThrowable
         //
         verifyException("org.apache.commons.lang3.concurrent.ConcurrentUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("", (Throwable) null);
      ConcurrentRuntimeException concurrentRuntimeException0 = new ConcurrentRuntimeException("", mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConcurrentRuntimeException concurrentRuntimeException0 = new ConcurrentRuntimeException();
      MockThrowable mockThrowable0 = new MockThrowable("03", concurrentRuntimeException0);
      ConcurrentRuntimeException concurrentRuntimeException1 = new ConcurrentRuntimeException(mockThrowable0);
      assertFalse(concurrentRuntimeException1.equals((Object)concurrentRuntimeException0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ConcurrentRuntimeException concurrentRuntimeException0 = new ConcurrentRuntimeException();
      ConcurrentRuntimeException concurrentRuntimeException1 = null;
      try {
        concurrentRuntimeException1 = new ConcurrentRuntimeException("03", concurrentRuntimeException0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Not a checked exception: org.evosuite.runtime.mock.java.lang.MockThrowable
         //
         verifyException("org.apache.commons.lang3.concurrent.ConcurrentUtils", e);
      }
  }
}
